import 'package:get/get_navigation/src/root/internacionalization.dart';

String selectedLanguage = "English";
String english = "English";
String marathi = "Marathi";

/// for the obsecure password

bool password = true;

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "english": "English",
          "marathi": "Marathi",
          "login": "Login",
          "signUp": "SignUp",
          "mobile": "Mobile Number",
          "otp": "We will send you One Time Password (OTP)",
          "o_login": "Officer Login       ",
          "userName": "User Name",
          "email": " Email",
          "district": " Select District",
          "taluka": " Select Taluka",
          "village": " Select Village",
          "mobToaster": "Enter Mobile Number",
          "ValidNobToaster": "Please Enter valid Number",
          "otpPage": "We have sent OTP on your Number.",
          "otpNotReceived": "Didn't received OTP ? ",
          "resendOtp": "Resend OTP",
          "otpToaster": "Please Enter valid OTP",
          "name": "Enter Your Name",
          "mobNo": "Enter Mobile Number",
          "mobNoToaster": " Mobile No already Exist",
          "loginToaster": "Login Successfully",
          "hello": "Hello..",
          "postGrievance": "Post Grievance",
          "trackGrievance": "Track Grievance",
          "submitFeedback": "Submit Feedback",
          "contact": "Contact Us",
          "postGrievanceD": "Post \nGrievance",
          "trackGrievanceD": "Track \nGrievance",
          "submitFeedbackD": "Submit \nFeedback",
          "contactD": "Contact Us",
          "faq": "FAQ\'S",
          "logout": "Logout",
          "chooseLang": "Choose Language",
          "logoutAlert": "Do you want to logout? ",
          "y": "Yes",
          "n": "No",
          "latestGrievanceResolved": "Latest Grievance Resolved",
          "tal": "Taluka",
          "dept": "Department",
          "nature": "Nature of Grievance",
          "resolvedDate": "Resolved Date : ",
          "regDate": "Reg.Date : ",
          "password": "Password ",
          "o_UserName": "User Name",
          "forgotPass": "Forgot Password      ",
          "citizenLogin": "Citizen's Login      ",

          /// for the post Grievance

          "pgDistrict": "District",
          "pgTaluka": "Taluka",
          "pgvillage": "village",
          "pgDept": "Department",
          "pgOffice": "Office",
          "pgNature": "Nature Of Grievance",
          "pgGrievanceDetails": "Grievance Details",
          "pgUploadDoc": " Upload image / Document",
          "pgNoFile": "  No file chosen ",
          "pgChooseFile": "Choose File",
          "pgSubmit": "SUBMIT",
          "officeToster": "Select Office",
          "deptToster": "Select Department",
          "natureToster": "Select Nature of Grievance",
          "detailsToster": "please Enter Grievance Details",
          "fileToster": "Please Upload image / Document",
          "selectVillage": "      Select Village",
          "selectOffice": "      Select Office",
          "type": " Type Here ",
          "contactus_desc":
              "If you want to know about the grievance redressal system or if you are facing any technical difficulty please call on below phone number.Our call center representative will help you",

          ///Notification
          "notification": " Notification ",
          "profile": " Profile",

          ///Track Grievance
          "search" : "Search",
          'enter_grievance_no' : 'Enter Grievance No.',
          'status':'Status',
          'view':'View',
          'geievance_id':'Grievance Id',
          'submission_date_time':'Submission Date & Time',
          'file_uploaded':'File Uploaded',
          'view_file': "View File",

          ///Submit Feedback
          "grievanceid" : "Grievance Id",
          "resolved" : "Resolved",
          "submissiond&t" : "Submission Date & Time",
          "naturegrievance" : "Nature Of Grievance",
          "fileuploaded" : "File Uploaded",
          "viewfile" : "View File",
          "submitreview" : "Your review will help us to give you a better experience",
          "comment" : "Comment",
          "typehere" : "Type Here",
          "satisfied" : "Satisfied",
          "disatisfied" : "Disatisfied",
          "municipalcor" : "Municipal Corporation",
          "dearcitizen" : "Dear Citizen,",
          "submitaction" : "Action has been taken against Grievance No. Looking forward for active contribution and cooperation from citizens od Osmanabad District.",
          "ok" : "Okay",
          "thanks" : "Thanks for your Response",
          "responsedetails" : "Response Details",
          "letterattach" : "Letter Attached",
          "regards" : "Regards,\nSamadhan team",
          "selectreason" : "Select Reason",
          "disatisfactionreason" : "Reason for Dissatisfaction",
          "connectionToastMsg" : "Please turn on your internet connection !!!",
          "name_missing_string" : "Please Enter user Name",
          "password_missing_string" : "Please Enter valid password",
          "samadhan_splash_screen" : "Samadhan",
          "public_grievance_redress_system_String" : "PUBLIC GRIEVANCE REDRESSAL SYSTEM",
          "splash_district" : "OSMANABAD DISTRICT",


        },
        'mr_IN': {
          "english": "इंग्रजी",
          "marathi": "मराठी",
          "login": "लॉगिन करा",
          "signUp": "साइनअप करा",
          "mobile": "मोबाइल नंबर",
          "otp": "आम्ही तुम्हाला वन टाइम पासवर्ड (OTP) पाठवू.",
          "o_login": "अधिकारी लॉगिन       ",
          "userName": "  नाव",
          "email": " ई-मेल आयडी",
          "district": " जिल्हा निवडा",
          "taluka": "तालुका निवडा",
          "village": " गाव निवडा",
          "mobToaster": "मोबाईल नंबर टाका",
          "ValidNobToaster": "वैध मोबाईल नंबर टाका",
          "otpPage": "आम्ही तुमच्या नंबरवर (OTP) पाठवला आहे.",
          "otpNotReceived": "OTP प्राप्त झाला नाही ? ",
          "resendOtp": "OTP पुन्हा पाठवा",
          "otpToaster": "कृपया वैध OTP प्रविष्ट करा",
          "name": "नाव प्रविष्ट करा",
          "mobNo": " मोबाईल नंबर टाका",
          "mobNoToaster": "मोबाईल नंबर आधीच अस्तित्वात आहे",
          "loginToaster": "यशस्वीरित्या लॉगइन केले",
          "hello": "नमस्कार..",
          "postGrievance": "तक्रार नोंद",
          "trackGrievance": "तक्रारची स्थिती",
          "submitFeedback": "अभिप्राय सबमिट करा",
          "contact": "संपर्क साधा",
          "postGrievanceD": "तक्रार नोंद",
          "trackGrievanceD": "तक्रारची स्थिती",
          "submitFeedbackD": "अभिप्राय सबमिट करा",
          "contactD": "संपर्क साधा",
          "faq": "वारंवार विचारले जाणारे प्रश्न",
          "logout": "लॉगआउट",
          "chooseLang": "भाषा निवडा",
          "logoutAlert": "तुम्हाला लॉगआऊट करायचं आहे का?",
          "y": "होय",
          "n": "नाही",
          "latestGrievanceResolved": "नवीनतम तक्रारीचे निराकरण",
          "tal": "तालुका",
          "dept": "विभाग",
          "nature": "तक्रारीचे स्वरूप",
          "resolvedDate": "निराकरण तारीख : ",
          "regDate": "रजि.तारीख : ",
          "password": "पासवर्ड",
          "o_UserName": "वापरकर्ता नाव",
          "forgotPass": "पासवर्ड विसरलात      ",
          "citizenLogin": "नागरिक लॉगिन       ",

          /// for the post Grievance

          "pgDistrict": "जिल्हा",
          "pgTaluka": "तालुका",
          "pgvillage": "गाव",
          "pgDept": "विभाग",
          "pgOffice": "ऑफीस",
          "pgNature": "तक्रारीचे स्वरूप",
          "pgGrievanceDetails": "तक्रार तपशील",
          "pgUploadDoc": "प्रतिमा / दस्तऐवज अपलोड करा",
          "pgNoFile": "फाइल निवडा ",
          "pgChooseFile": "फाइल निवडा",
          "pgSubmit": "जतन करा",
          "officeToster": "ऑफीस निवडा",
          "deptToster": "विभाग निवडा",
          "natureToster": "तक्रारीचे स्वरूप निवडा",
          "detailsToster": "कृपया तक्रार तपशील प्रविष्ट करा",
          "fileToster": "कृपया प्रतिमा / दस्तऐवज अपलोड करा",
          "selectVillage": "     गाव निवडा",
          "selectOffice": "     ऑफीस निवडा",
          "type": " येथे टाइप करा  ",

          ///Notification
          "notification": " सूचना ",
          "profile": " प्रोफाइल ",
          "contactus_desc":

          "तुम्हाला तक्रार निवारण प्रणालीबद्दल जाणून घ्यायचे असल्यास किंवा तुम्हाला काही तांत्रिक अडचण येत असल्यास कृपया खालील फोन नंबरवर कॉल करा. आमचा कॉल सेंटर प्रतिनिधी तुम्हाला मदत करेल.",
       ///Track Grievance
         "search" : "शोधा",
          'enter_grievance_no' : 'तक्रार क्र. टाका ',
          'status':'स्थिती',
          'view':'पाहा',
          'geievance_id':'तक्रार नंबर',
          'submission_date_time':'सबमिशनची तारीख आणि वेळ',
          'file_uploaded':'फाइल अपलोड केली',
          'view_file':'फाइल पाहा',
          ///Submit Feedback
          "grievanceid" : "तक्रार आयडी",
          "resolved" : "निराकरण केले",
          "submissiond&t" : "सबमिशनची तारीख आणि वेळ",
          "naturegrievance" : "तक्रारीचे स्वरूप",
          "fileuploaded" : "फाइल अपलोड केली",
          "viewfile" : "फाइल पहा",
          "submitreview" : "तुमचे पुनरावलोकन आम्हाला तुम्हाला अधिक चांगला अनुभव देण्यास मदत करेल",
          "comment" : "टिप्पणी",
          "typehere" : "येथे लिहा",
          "satisfied" : "समाधानी",
          "disatisfied" : "असमाधानी",
          "municipalcor" : "महानगरपालिका",
          "dearcitizen" : "प्रिय नागरिक,",
          "submitaction" : "प्रतक्रार क्रमांक  वर कारवाई करण्यात आली आहे. उस्मानाबाद जिल्ह्यातील नागरिकांकडून सक्रिय योगदान आणि सहकार्याची अपेक्षा आहे.",
          "ok" : "ठीक आहे",
          "thanks" : "तुमच्या प्रतिसादाबद्दल धन्यवाद",
          "responsedetails" : "प्रतिसाद तपशील",
          "letterattach" : "पत्र जोडले",
          "regards" : "विनम्र,\nसमाधान टीम",
          "selectreason" : "कारण निवडा",
          "disatisfactionreason" : "असंतोषाचे कारण",
          "connectionToastMsg" : "कृपया आपले इंटरनेट कनेक्शन चालू करा !!!",
          "name_missing_string" : "कृपया वैध नाव प्रविष्ट करा",
          "password_missing_string" : "कृपया वैध पासवर्ड प्रविष्ट करा",
          "samadhan_splash_screen" : "समाधान",
          "public_grievance_redress_system_String" : "नागरिक तक्रार निवारण प्रणाली",
          "splash_district" : "उस्मानाबाद जिल्हा",



        },
      };
}

String postGrievance = "Grievance Posted Successfully";
String emptyPostGrievance = "Please fill all details";
